version: '3.8'

services:
  # Serviço de Banco de Dados: SQL Server
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: pizza_sql_facul
    environment:
      - ACCEPT_EULA=Y
      # Senha fácil e sem segurança, usada para acesso SA
      - MSSQL_SA_PASSWORD=SenhaFacul123 
    ports:
      - "1433:1433"
    volumes:
      - pizza_data_facul:/var/opt/mssql
    restart: always

volumes:
  pizza_data_facul: